name: splitease
region: nyc

services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    build_command: bash build.sh
    run_command: gunicorn splitease.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DEBUG
        value: "False"
        scope: RUN_AND_BUILD_TIME
      - key: ALLOWED_HOSTS
        value: ${APP_DOMAIN}
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
      - key: CSRF_TRUSTED_ORIGINS
        value: https://${APP_DOMAIN}
        scope: RUN_AND_BUILD_TIME

databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-dev-database
